[package]
name = "day21"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../../../utils" }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
